Add support for running portmaster on a mac for testing purposes

diff --git a/ports/global/global-functions b/ports/global/global-functions
--- a/ports/global/global-functions
+++ b/ports/global/global-functions
@@ -9,7 +9,7 @@
 # -----------------------------------------------------
 # Utilizing DIR instead of ./ means the script can be called from any directory
 #
-# All files in this script should suppport the $ROOT_DIR variable which will default to ''.  This allows
+# All files in this script should suppport the $__ROOT_DIR variable which will default to ''.  This allows
 # creating mock environments for testing
 #
 # Functions are designed to be called in the format:
@@ -17,37 +17,45 @@
 # DEV NOTE: If debug output is needed in a function, output information with `echo_err` (stderr) as
 # anything output to stdout will be included in the returned device, etc
 
-ROOT_DIR=
+## Initialize internal global variables
+### - all should start with __ and be CAPITALIZED to avoid collisions with other globals
+### - all other variables should be local
+__ROOT_DIR=""  # Allows simulating a file system
+__DEVICE=""    # Cache for detecting device as it should not change
+__OS=""        # Cache for detecting OS as it should not change 
 
 # Gets the current device:
 #  Supported devices: rg351p, rg351p (rg351m), rg351mp, oga, rk2020, ogs (same as rgb10max), chi, unknown
 function get_device() {
 
-  local param_device="unknown"
-  if [[ -e "${ROOT_DIR}/dev/input/by-path/platform-ff300000.usb-usb-0:1.2:1.0-event-joystick" ]]; then
-    #anbernic rg351v and rg351p
-    if [[ -e "${ROOT_DIR}/dev/input/by-path/platform-rg351-keys-event" ]]; then #volume buttons
-      param_device="rg351v"
-    else
-      param_device="rg351p"
+  if [[ -z "${__DEVICE}" ]]; then
+    __DEVICE="unknown"
+    if [[ -e "${__ROOT_DIR}/dev/input/by-path/platform-ff300000.usb-usb-0:1.2:1.0-event-joystick" ]]; then
+      #anbernic rg351v and rg351p
+      if [[ -e "${__ROOT_DIR}/dev/input/by-path/platform-rg351-keys-event" ]]; then #volume buttons
+        __DEVICE="rg351v"
+      else
+        __DEVICE="rg351p"
+      fi
+    elif [[ -e "${__ROOT_DIR}/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
+      if [[ -f "${__ROOT_DIR}/etc/emulationstation/es_input.cfg" ]] \
+         && grep -q "190000004b4800000010000001010000" "${__ROOT_DIR}/etc/emulationstation/es_input.cfg" &> /dev/null; then
+        __DEVICE="oga"
+    	else
+    	  __DEVICE="rk2020"
+    	fi
+    elif [[ -e "${__ROOT_DIR}/dev/input/by-path/platform-odroidgo3-joypad-event-joystick" ]]; then
+      if [[ -e "${__ROOT_DIR}/dev/input/by-path/platform-rg351-keys-event" ]]; then
+        __DEVICE="rg351mp"
+      else
+        __DEVICE="ogs"
+      fi
+    elif [[ -e "${__ROOT_DIR}/dev/input/by-path/platform-gameforce-gamepad-joystick" ]]; then
+      __DEVICE="chi"
     fi
-  elif [[ -e "${ROOT_DIR}/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
-    if [[ -f "${ROOT_DIR}/etc/emulationstation/es_input.cfg" ]] \
-       && grep -q "190000004b4800000010000001010000" "${ROOT_DIR}/etc/emulationstation/es_input.cfg" &> /dev/null; then
-      param_device="oga"
-  	else
-  	  param_device="rk2020"
-  	fi
-  elif [[ -e "${ROOT_DIR}/dev/input/by-path/platform-odroidgo3-joypad-event-joystick" ]]; then
-    if [[ -e "${ROOT_DIR}/dev/input/by-path/platform-rg351-keys-event" ]]; then
-      param_device="rg351mp"
-    else
-      param_device="ogs"
-    fi
-  elif [[ -e "${ROOT_DIR}/dev/input/by-path/platform-gameforce-gamepad-joystick" ]]; then
-    param_device="chi"
   fi
-  echo "${param_device}"
+  echo "${__DEVICE}"
+  __DEVICE=""
 }
 
 # This is the 'param_device' to pass to oga_controls.
@@ -105,19 +113,24 @@ function get_sdl_controls() {
 #  Options: ArkOS, 351ELEC, TheRA, ubuntu, unknown
 #  NOTE: ubuntu is to be used as fallback for testing off-device (mostly applicable for portmaster)
 function get_os() {
-  local param_os="unknown"
-
-  if [[ -f "${ROOT_DIR}/boot/rk3326-rg351v-linux.dtb" || -d "${ROOT_DIR}/opt/system/Advanced/" ]]; then
-    param_os="ArkOS"
-  elif [[ -e "${ROOT_DIR}/storage/.config/.OS_ARCH" ]]; then
-    param_os="351ELEC"
-  elif [[ -e "${ROOT_DIR}/usr/share/plymouth/themes/text.plymouth" \
-          && $(grep "title=" "${ROOT_DIR}/usr/share/plymouth/themes/text.plymouth") == *"TheRA"* ]]; then
-    param_os="TheRA"
-  elif grep -q "ID=ubuntu" ${ROOT_DIR}/etc/os-release &> /dev/null; then
-    param_os="ubuntu"
+  if [[ -z "$__OS" ]]; then
+    __OS="unknown"
+    
+    if [[ -f "${__ROOT_DIR}/boot/rk3326-rg351v-linux.dtb" || -d "${__ROOT_DIR}/opt/system/Advanced/" ]]; then
+      __OS="ArkOS"
+    elif [[ -e "${__ROOT_DIR}/storage/.config/.OS_ARCH" ]]; then
+      __OS="351ELEC"
+    elif [[ -e "${__ROOT_DIR}/usr/share/plymouth/themes/text.plymouth" \
+            && $(grep "title=" "${__ROOT_DIR}/usr/share/plymouth/themes/text.plymouth") == *"TheRA"* ]]; then
+      __OS="TheRA"
+    elif grep -q "ID=ubuntu" ${__ROOT_DIR}/etc/os-release &> /dev/null; then
+      __OS="ubuntu"
+    elif [[ $OSTYPE == 'darwin'* ]]; then
+      __OS="mac"
+    fi
   fi
-  echo "${param_os}"
+  echo "${__OS}"
+  __OS=""
 }
 
 # Whether to use sudo
@@ -137,22 +150,24 @@ function get_sudo() {
 #TODO: understand why this is sometimes 'roms' dir
 function get_tools_dir() {
   os=$(get_os)
-  local toolsfolderloc="${ROOT_DIR}/roms/ports"
+  local toolsfolderloc="${__ROOT_DIR}/roms/ports"
   if [[ "351ELEC" == "${os}" ]]; then
-    toolsfolderloc="${ROOT_DIR}/storage/roms/ports"
+    toolsfolderloc="${__ROOT_DIR}/storage/roms/ports"
   elif [[ "TheRA" == "${os}" ]]; then
     if [ -d "/opt/tools/PortMaster/" ]; then
-      toolsfolderloc="${ROOT_DIR}/opt/tools"
+      toolsfolderloc="${__ROOT_DIR}/opt/tools"
     else
-      toolsfolderloc="${ROOT_DIR}/roms/ports"
+      toolsfolderloc="${__ROOT_DIR}/roms/ports"
     fi
   elif [[ "ArkOS" == "${os}" ]]; then
-    toolsfolderloc="${ROOT_DIR}/opt/tools"
+    toolsfolderloc="${__ROOT_DIR}/opt/tools"
     if [ -d "/opt/system/Tools/PortMaster/" ]; then
-      toolsfolderloc="${ROOT_DIR}/opt/system/Tools"
+      toolsfolderloc="${__ROOT_DIR}/opt/system/Tools"
     else
-      toolsfolderloc="${ROOT_DIR}/roms/ports"
+      toolsfolderloc="${__ROOT_DIR}/roms/ports"
     fi
+  elif [[ "mac" == "${os}" ]]; then
+    toolsfolderloc="${__ROOT_DIR}/var/tmp/portmaster/ports"
   fi
   echo "${toolsfolderloc}"
 }
@@ -160,13 +175,15 @@ function get_tools_dir() {
 function get_roms_dir() {
   local os
   os=$(get_os)
-  local romsfolderloc="${ROOT_DIR}/opt/roms"
+  local romsfolderloc="${__ROOT_DIR}/opt/roms"
   if [[ "351ELEC" == "${os}" ]]; then
-    romsfolderloc="${ROOT_DIR}/storage/roms/"
+    romsfolderloc="${__ROOT_DIR}/storage/roms/"
   elif [[ "TheRA" == "${os}" ]]; then
-    romsfolderloc="${ROOT_DIR}/opt/system/Roms"
+    romsfolderloc="${__ROOT_DIR}/opt/system/Roms"
   elif [[ "ArkOS" == "${os}" ]]; then
-    romsfolderloc="${ROOT_DIR}/$(get_arkos_roms_dir_name)"
+    romsfolderloc="${__ROOT_DIR}/$(get_arkos_roms_dir_name)"
+  elif [[ "mac" == "${os}" ]]; then
+    romsfolderloc="${__ROOT_DIR}/var/tmp/portmaster/roms"
   fi
   echo "${romsfolderloc}"
 }
@@ -187,7 +204,7 @@ function get_console() {
   local os
   os=$(get_os)
   local console="/dev/tty0"
-  if [[ "ubuntu" == "${os}" || "unknown" == "${os}" ]]; then
+  if [[ "ubuntu" == "${os}" || "unknown" == "${os}" || "mac" == "${os}" ]]; then
     console="/dev/stdout"
   fi
   echo "${console}"
@@ -206,8 +223,19 @@ function get_hotkey() {
   echo "${hotkey}"
 }
 
+function get_grep() {
+  local grep="grep"
+  if [[ "$(get_os)" == "mac" ]]; then
+    grep="ggrep"
+  fi
+  echo "${grep}"
+}
+function get_wget() {
+   echo "wget"
+}
 function in_china() {
-  ISITCHINA=$(curl -s --connect-timeout 30 -m 60 http://demo.ip-api.com/json | grep -Po '"country":.*?[^\\]"')
+  local grep=$(get_grep)
+  ISITCHINA=$(curl -s --connect-timeout 30 -m 60 http://demo.ip-api.com/json | ${grep} -Po '"country":.*?[^\\]"' )
   local in_china=false
   if [[ "$ISITCHINA" == "\"country\":\"China\"" ]]; then
     in_china=true
@@ -332,16 +360,11 @@ function dialog_initialize() {
     HEIGHT="20"
     WIDTH="60"
   fi
-  # check_install curl
-  if ! which curl &> /dev/null; then
-    echo "curl not found"
-    $esudo apt update && $esudo apt install -y curl --no-install-recommends
-  fi
+  install_package curl
   
   # check_install dialog
-  if ! which dialog &> /dev/null; then
-    echo "dialog not found"
-    $esudo apt update && $esudo apt install -y dialog --no-install-recommends
+  if ! check_package dialog; then
+    install_package "dialog"
     if [[ "$os" == "ArkOS" && "$device" == "rg351p" ]]; then
   	  #Make sure sdl2 wasn't impacted by the install of dialog for the 351P/M
       $esudo ln -sfv /usr/lib/aarch64-linux-gnu/libSDL2-2.0.so.0.14.1 /usr/lib/aarch64-linux-gnu/libSDL2-2.0.so.0
@@ -352,9 +375,45 @@ function dialog_initialize() {
     $esudo timedatectl set-ntp 1
   fi
   __TMP_FILE=$(mktemp dialog.XXX 2>/dev/null) || __TMP_FILE=/tmp/dialog-$$
+  console_clear
   run_at_exit dialog_exit
 }
-
+function install_package() {
+  local package="$1"
+  local brew_package="${2:-}"
+  local esudo="$(get_sudo)"
+  if [[ -z "${brew_package}" ]]; then
+    brew_package="$package"
+  fi
+  if ! check_package "$package" "$brew_package"; then
+    if [[ "$(get_os)" == "mac" ]]; then
+        if ! which brew &> /dev/null; then
+          echo "'brew' required on Mac to install packages. Please install brew: https://brew.sh/"
+          exit 1
+        fi
+        echo "${brew_package} required.  Installing with brew..."
+        brew install ${brew_package}
+    else
+        echo "${package} required.  Installing with apt..."
+        $esudo apt update && $esudo apt install -y $package --no-install-recommends
+    fi
+  fi
+}
+function check_package() {
+  local package="$1"
+  local brew_package="${2:-}"
+  if [[ -z "${brew_package}" ]]; then
+    brew_package="$package"
+  fi
+  if [[ "$(get_os)" == "mac" ]]; then
+    package="$brew_package"
+  fi
+  if ! which "$package" &> /dev/null; then
+      return 1
+  fi
+  
+  return 0
+}
 function dialog_exit() {
   echo_err "removing dialog temp file: ${__TMP_FILE}"
   rm -f "${__TMP_FILE}"
@@ -422,7 +481,8 @@ function dialog_download() {
   esudo="$(get_sudo)"
 
   echo_err "download: $url file: $file message: $message console: $console"
-  if $esudo wget -t 3 -T 60 -q --show-progress "${url}" -O ${file} 2>&1 | stdbuf -oL sed -E 's/\.\.+/---/g'| dialog \
+  install_package wget
+  if $esudo $(get_wget) -t 3 -T 60 -q --show-progress "${url}" -O ${file} 2>&1 | stdbuf -oL sed -E 's/\.\.+/---/g'| dialog \
                      --progressbox "$message" "$HEIGHT" "$WIDTH" &> ${console}; then
     return 0
   else
@@ -432,6 +492,10 @@ function dialog_download() {
 
 function is_network_connected() {
   local gateway
+  local os="$(get_os)"
+  if [[ "$os" == "mac" ]]; then
+    install_package "ip" "iproute2mac"
+  fi
   gateway=$(ip route | awk '/default/ { print $3 }')
   if [ -z "$gateway" ]; then
     return 1
@@ -470,9 +534,14 @@ if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   echo "DEVICE=$(get_device)"
   echo "TOOLSDIR=$(get_tools_dir)"
   echo "ROMSDIR=$(get_roms_dir)"
+  echo "PORTSDIR=$(get_ports_dir)"
   echo "CONSOLE=$(get_console)"
   echo "HOTKEY=$(get_hotkey)"
+  echo "GREP=$(get_grep)"
   echo "IN_CHINA=$(in_china)"
   echo "OGA_DEVICE=$(get_oga_device)"
   echo "SDL_DEVICE_ID=$(get_sdl_device_id)"
+  echo "IS_NETWORK_CONNECTED=$(is_network_connected)"
+  echo "GITHUB_ORG=$(get_github_org)"
+
 fi
